### ISSUE TITLE
Native Controler Steamdeck

### ISSUE THREAD

**Issue by KingsCookie** [TheMulhima/Lumafly#95]
### Lumafly Version

latest

### Hollow Knight Version

latest

### Steps to Reproduce

Install lumafly on steamdeck

### Expected Behaviour

The game to function

### Actual Behaviour

When on steamdeck, the mod makes it so the native controler of Steam deck isn't detected anymore.
It's an issue because then the cannot be played anymore

### Errors and Logs

nothing

**Comment by BadMagic100** [comment]
**__Mods/Controller not working correctly on Steam Deck__**
Issue: *Steam Deck installs the Windows version of HK, then runs it in proton. This would be fine except that you install Linux Lumafly, which replaces the Assembly-Csharp with the Linux version, and then it doesn't like to work correctly on "Windows" anymore*

Solution: Go to the HK Library page, select Properties -> Compatibility, check "Force the use of a specific steam play compatibility tool", and select "Steam Linux Runtime" *(Note: not the sniper or soldier versions)*

This will reinstall the Linux version of the game, and move some files around, so you'll need to select "Change Paths" in Lumafly and change it to the new install path, then reinstall your mods. After this, everything should be working.

**Comment by Ruttie2006** [comment]
Hi @KingsCookie, is this still an issue?

**Comment by Trikzon** [comment]
I am getting this (on Linux Desktop, not Steam Deck) with both the Proton version and the Linux version.

**Comment by retcinder** [comment]
Nevermind, I was experiencing a different issue. Ignore this.
~~I am experiencing this on my Steam Deck (doesn't run SteamOS, uses CachyOS) on the Proton version.~~

~~I cannot utilise the native linux version due to it having a very buggy controller implementation which makes the game unplayable with my Switch Pro Controller. (Added this bit here in case someone recommends me to use the advice given by BadMagic)~~

**Comment by KingsCookie** [comment]
> Hi [@KingsCookie](https://github.com/KingsCookie), is this still an issue?

Yes, it is still an issue. I managed to find a work around by reassigning all my keys but the native controller is still not detected.

**Comment by Ruttie2006** [comment]
> > Hi [@KingsCookie](https://github.com/KingsCookie), is this still an issue?
> 
> Yes, it is still an issue. I managed to find a work around by reassigning all my keys but the native controller is still not detected.

Did you try the steps listed in the post by BadMagic?
I suspect this issue is not caused by Lumafly, but rather by the ModdingAPI

**Comment by KingsCookie** [comment]
> Did you try the steps listed in the post by BadMagic? I suspect this issue is not caused by Lumafly, but rather by the ModdingAPI

So I tried it and it worked for me, thanks.
You can probably close the issue.
Sorry for taking so long, I had issues with my deck
